# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: "node-app"
#     static_configs:
#       - targets: ["node-app:3000"]


global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]
