name: vbank
version: "3.9"

services:
  sqlserver: # MSSQL Server
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "admin@123" #MSSQl Password
    ports:
      - "1435:1433"  # Local PC port 1435 -> Container port 1433
    volumes:
      - sqlserverdata:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  # mongodb:
  #   image: mongodb/mongodb-community-server:8.0-ubi8
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin@123
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  # api-gateway:
  #   #build: .
  #   image: api-gateway
  #   container_name: api-gateway
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #   ports:
  #     - "3000:3000"

  # auth-server:
  #   image: auth-service
  #   container_name: auth-service
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #     RABBITMQ_URL: amqp://rabbitmq:5672
  #     MONGO_DB_URL: mongodb://host.docker.internal:27017
  #   ports:
  #     - "3001:3001"



volumes:
  rabbitmq_data:
  sqlserverdata:
  redis_data:
 # mongo_data:
